model:
  vocab_size: 16
  hidden_size: 256
  intermediate_size: 768
  num_layers: 8
  num_attention_heads: 8
  num_kv_heads: 8
  max_position: 354
  rms_norm_eps: 1e-6
  dropout: 0.0

training:
  strategy: "standard"
  confidence_threshold: 0.9
  mode: "standard" # [standard, x0, mixed]
  K: 8
  data_ratio: 1.0
  learning_rate: 3e-4
  weight_decay: 0.01
  num_epochs: 6
  max_grad_norm: 1.0
  batch_size: 128 # This should now be global batch size
  warmup_steps: 500
  logging_steps: 100
  eval_steps: 1000
  save_steps: 10000
  ema: null
  eos_id: null

validation:
  batch_size: 1024
  val_dir: "data/maze17x17"
  ratio: 1
  sampling: 
    temperature: 0.0
    confidence: ["top_k"]
    unmasking_num: [1]
    # edit_freq: [-1, 3, 9]
    # edit_step: [4]
  track: true

data:
  mask_id: 0
  dataset: "maze"
  data_dir: ${validation.val_dir}
  val_ratio: 0.001
  seed: 123
  mmap: false
  training:
    # per_gpu_batch_size: ${training.batch_size} # This will be set in the training script based on the world size
    cpus: 4

wandb:
  wandb: true
  project: "maze17x17-pretraining"
  name: "maze-${training.strategy}-s${data.seed}"
  entity: "your-entity-here"