grid_size: 4  # n; sets model.vocab_size = n^2+2, model.max_position = 2*n^4, data.mask_id = n^2+1

model:
  hidden_size: 256
  intermediate_size: 768
  num_layers: 8
  num_attention_heads: 8
  num_kv_heads: 8
  rms_norm_eps: 1e-6
  dropout: 0.0

training:
  strategy: "progressive_edit"
  confidence_threshold: 0.9
  mode: "standard" # [standard, x0, mixed]
  K: 8
  data_ratio: 1.0
  learning_rate: 3e-4
  weight_decay: 0.01
  max_steps: 2000000
  num_epochs: 6
  max_grad_norm: 1.0
  batch_size: 128
  warmup_steps: 1000
  logging_steps: 100
  eval_steps: 5000
  save_steps: 10000
  save_checkpoints: false
  ema: null
  eos_id: null

validation:
  val_dir: "data/sudoku_n4"
  ratio: 0.01
  sampling:
    temperature: 0.0
    confidence: ["top_k"]
    unmasking_num: [1, 3]
    edit_freq: [-1, 3, 9]
    edit_step: [4]
  track: true

data:
  dataset: "sudoku"
  data_dir: "data/sudoku_n4"
  sudoku_type: "new"
  val_ratio: 0.05
  seed: 123
  mmap: false
  training:
    per_gpu_batch_size: ${training.batch_size}
    cpus: 4

wandb:
  wandb: true
  project: "puma-mdm-pretraining"
  name: "sudoku-puma-edit-n4-bs32-s${data.seed}"
  entity: "zw2700"
