# -------------------------------------------------------
# Sudoku data collactor opt for our DataBundle format
# -------------------------------------------------------

import json
import os
import numpy as np
import torch
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader, random_split

class MazeDataset(Dataset):
    """
    Assume we have the all_inputs.npy and all_labels.npy in the data directory
    these can be generated by the sudoku_HRM.py script
    """

    def __init__(self, data_dir: str):
        # we sue mmap if the .npy's size is too large
        self.data_dir = data_dir

        train_label_path = os.path.join(data_dir, "train_labels.npy")
        train_pmask_path = os.path.join(data_dir, "train_prompt_mask.npy")
        if os.path.exists(train_label_path) and os.path.exists(train_pmask_path):
            print(f"Loading data from {train_label_path} and {train_pmask_path}...")
            self.labels = np.load(train_label_path)
            self.prompt_mask = np.load(train_pmask_path)
        else:
            data_file = os.path.join(data_dir, f"train.jsonl")
            assert os.path.exists(data_file), f"Data file {data_file} does not exist"
            seqs = []
            p_masks = []
            print(f"Loading data from {data_file}...")
            with open(data_file, "r") as f:
                for line in tqdm(f):
                    d = json.loads(line)
                    seqs.append(d["sequence"])
                    p_mask = np.zeros(len(d["sequence"]), dtype=bool)   
                    p_mask[:d["prompt_length"]] = 1
                    p_masks.append(p_mask)
            self.labels = np.array(seqs)
            self.prompt_mask = np.array(p_masks)
            np.save(train_label_path, self.labels)
            np.save(train_pmask_path, self.prompt_mask)

        # process for test file as well
        test_label_path = os.path.join(data_dir, "test_labels.npy")
        test_pmask_path = os.path.join(data_dir, "test_prompt_mask.npy")
        if not (os.path.exists(test_label_path) and os.path.exists(test_pmask_path)):
            data_file = os.path.join(data_dir, f"test.jsonl")
            assert os.path.exists(data_file), f"Data file {data_file} does not exist"
            seqs = []
            p_masks = []
            print(f"Loading data from {data_file}...")
            with open(data_file, "r") as f:
                for line in tqdm(f):
                    d = json.loads(line)
                    seqs.append(d["sequence"])
                    p_mask = np.zeros(len(d["sequence"]), dtype=bool)   
                    p_mask[:d["prompt_length"]] = 1
                    p_masks.append(p_mask)
            test_labels = np.array(seqs)
            test_prompt_mask = np.array(p_masks)
            np.save(test_label_path, test_labels)
            np.save(test_pmask_path, test_prompt_mask)
    
    def __len__(self):
        return self.labels.shape[0]

    def __getitem__(self, idx):
        # np.load with mmap returns a view, copy() to avoid weirdness
        # np.load with mmap returns a view, copy() to avoid weirdness
        lab = torch.from_numpy(self.labels[idx].copy()).long()
        prompt_mask = torch.from_numpy(self.prompt_mask[idx].copy()).bool()
        return {"labels": lab, "prompt_mask": prompt_mask}


def split_maze(data_dir: str, val_ratio: float = 0.001, seed: int = 2025):
    dataset= MazeDataset(data_dir)
    n = len(dataset)

    # split
    n_val, n_train = int(n * val_ratio), n - int(n * val_ratio)

    # reproducible split
    g = torch.Generator().manual_seed(seed)
    train_data, val_data = random_split(dataset, [n_train, n_val], generator=g)
    
    return train_data, val_data


if __name__ == "__main__":
    data_dir = "data/maze17x17_dfs"
    train_data, val_data = split_maze(data_dir)
    print(len(train_data), len(val_data))
    print(val_data[0])