# Adapted from MaxRL codebase by Guanning Zeng
# We change the representation of the maze: We represent the maze as a list of empty cells coordinates

from argparse import Action
import numpy as np
import random
from collections import deque
import json
import os

class Maze_Env:
    def __init__(self, start):
        self.state = start
        self.action = 0
        self.reward = 0
        self.done = False
        self.info = {}
    
    def step(self, action):
        pass
class MazeGenerator:
    def __init__(self, size=7, seed=None, algorithm='prim'):
        """
        size: Maze size (preferably odd numbers, e.g. 5, 7, 9, 11...)
        seed: Random seed for reproducibility
        """
        self.algorithm = algorithm
        assert algorithm in ['prim', 'dfs'], "Invalid algorithm"
        self.size = size
        self.rng = random.Random(seed)
        # Maze grid: 1 for wall, 0 for path
        self.grid = np.ones((size, size), dtype=int)
        self.start = (1, 1)
        self.goal = (size - 2, size - 2)
        
        # Action space mapping
        self.actions = {
            0: (-1, 0), # UP
            1: (1, 0),  # DOWN
            2: (0, -1), # LEFT
            3: (0, 1)   # RIGHT
        }
        # 任务：修改action_names为不带尖括号的格式，用于文本训练数据生成
        # 实现方案：使用UP、DOWN、LEFT、RIGHT作为action token名称
        self.action_names = ['UP', 'DOWN', 'LEFT', 'RIGHT']

    def generate(self, algorithm=None):
        """
        Generate the maze using the Recursive Backtracker algorithm.
        The maze generated by this algorithm has these properties:
        1. Good connectivity
        2. Twisting main path, many dead ends (suitable for testing agent exploration)
        """
        # Reset grid to all walls
        self.grid.fill(1)
        
        # Start carving from the starting point
        if algorithm is None:
            algorithm = self.algorithm
            
        if self.algorithm == 'dfs':
            self.carve_passages_from(self.start[0], self.start[1])
        elif self.algorithm == 'prim':
            self.prim()
        
        # Ensure start and goal are empty
        self.grid[self.start] = 0
        self.grid[self.goal] = 0
        
        # [Optional] Randomly add an opening: add some randomness, avoid unique solution only
        # This is sometimes good for RL exploration, to prevent falling into local optimum too early
        # if self.rng.random() < 0.1:
        #     rx, ry = self.rng.randint(1, self.size-2), self.rng.randint(1, self.size-2)
        #     self.grid[rx, ry] = 0
            
        return self.grid
    
    def prim(self):
        """
        Generate the maze using Prim's algorithm.
        Task: Add Prim's algorithm maze generation method
        Approach: Start from start point, maintain a frontier of walls, randomly knock down a wall, until all reachable area is visited
        Properties: The generated maze has relatively uniform paths, fewer dead ends
        """
        # Start from the starting point
        start_x, start_y = self.start[0], self.start[1]
        self.grid[start_x, start_y] = 0
        
        # Frontier: stores expandable wall positions (walls two steps away from carved area)
        frontier = []
        directions = [(0, 2), (2, 0), (0, -2), (-2, 0)]
        
        # Initialize frontier: add walls that are two steps around the start
        for dx, dy in directions:
            nx, ny = start_x + dx, start_y + dy
            if 0 < nx < self.size - 1 and 0 < ny < self.size - 1:
                if self.grid[nx, ny] == 1:
                    frontier.append((nx, ny))
        
        # Main loop: randomly pick a frontier wall and knock it down
        while frontier:
            # Randomly select a frontier wall
            idx = self.rng.randint(0, len(frontier) - 1)
            fx, fy = frontier.pop(idx)
            
            # Find already carved region adjacent to this frontier wall
            neighbors = []
            for dx, dy in directions:
                nx, ny = fx + dx, fy + dy
                if 0 <= nx < self.size and 0 <= ny < self.size:
                    if self.grid[nx, ny] == 0:
                        neighbors.append((nx, ny))
            
            # Randomly choose an adjacent carved region, knock down the wall in between
            if neighbors:
                nx, ny = self.rng.choice(neighbors)
                # Compute the middle wall position
                mid_x, mid_y = (fx + nx) // 2, (fy + ny) // 2
                self.grid[mid_x, mid_y] = 0
                self.grid[fx, fy] = 0
                
                # Add new frontiers
                for dx, dy in directions:
                    new_x, new_y = fx + dx, fy + dy
                    if 0 < new_x < self.size - 1 and 0 < new_y < self.size - 1:
                        if self.grid[new_x, new_y] == 1 and (new_x, new_y) not in frontier:
                            frontier.append((new_x, new_y))
                            
                            
    def carve_passages_from(self, cx, cy):
        """Recursive backtracking carving algorithm"""
        directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
        self.rng.shuffle(directions)

        for dx, dy in directions:
            nx, ny = cx + dx, cy + dy        # Neighbor
            mx, my = cx + 2*dx, cy + 2*dy    # Two steps away

            # Check if within bounds and not yet carved
            if 0 <= mx < self.size and 0 <= my < self.size:
                if self.grid[mx, my] == 1: # If two steps away position is a wall
                    self.grid[nx, ny] = 0  # Carve the middle wall
                    self.grid[mx, my] = 0  # Carve the target point
                    self.carve_passages_from(mx, my)

    def get_state_action_pairs(self):
        """
        Get the state-action pairs for the maze.
        """
        optimal_actions = self.solve_bfs()
        state_action_pairs = {}
        cx, cy = self.start[0], self.start[1]
        for i in range(len(optimal_actions)):
            action = optimal_actions[i]
            state_action_pairs[(cx, cy)] = self.action_names[action]
            dx, dy = self.actions[action]
            cx, cy = cx + dx, cy + dy
        return state_action_pairs
    
    def format_data(self):
        
        walls = []
        for r in range(self.size):
            for c in range(self.size):
                if self.grid[r, c] == 1:
                    walls.append(f"({r},{c})")
        
        env = {
            "Walls": {', '.join(walls)},
            "Start": self.start,
            "Goal": self.goal,
        }
        policy = self.get_state_action_pairs()
        episode = {
            "env": env,
            "policy": policy,
            "optimal_len": len(policy.keys()),
        }
        return episode  
    
    def solve_bfs(self):
        """
        Solve the maze using BFS (Breadth-First Search) to find the shortest path.
        This is your SFT Ground Truth (y*).
        """
        queue = deque([(self.start, [])]) # (current_pos, path_of_actions)
        visited = set([self.start])

        while queue:
            (cx, cy), path = queue.popleft()

            # Found goal
            if (cx, cy) == self.goal:
                return path # Returns action sequence, e.g. [1, 3, 3, 0...]

            # Try all 4 directions
            for action_idx, (dx, dy) in self.actions.items():
                nx, ny = cx + dx, cy + dy

                # Check bounds and collisions
                if 0 <= nx < self.size and 0 <= ny < self.size:
                    if self.grid[nx, ny] == 0 and (nx, ny) not in visited:
                        visited.add((nx, ny))
                        new_path = path + [action_idx]
                        queue.append(((nx, ny), new_path))
        
        return None # No solution (should not happen in principle)

    def to_prompt_string(self):
        """
        Converts the maze state to a prompt string for LLM input.
        Format: includes all wall coordinates and goals.
        """
        walls = []
        for r in range(self.size):
            for c in range(self.size):
                if self.grid[r, c] == 1:
                    walls.append(f"({r},{c})")
        
        prompt = (
            # f"Maze Size: {self.size}x{self.size}\n"
            f"Walls: {', '.join(walls)}\n"
            f"Start: {self.start}\n"
            f"Goal: {self.goal}\n"
            f"State: (0,0)\n"
            f"Action: "
        )
        return prompt

    def render_ascii(self):
        """Print the maze in the console, useful for debugging and inspection"""
        chars = {1: '#', 0: ' ', 2: 'S', 3: 'G'}
        temp_grid = self.grid.copy()
        temp_grid[self.start] = 2
        temp_grid[self.goal] = 3
        
        print("-" * (self.size + 2))
        for row in temp_grid:
            print("|" + "".join([chars[x] for x in row]) + "|")
        print("-" * (self.size + 2))
    
    def to_text_sequence(self):
        """
        任务：将迷宫转换为文本格式的训练数据序列
        格式：[<bos>, GRID_START, c_1..c_{K²}, GRID_END, PATH_START, a_1..a_T, DONE, <eos>]
        实现方案：
        1. 将网格按行展开，每个cell转换为对应的token（START、GOAL、WALL、PATH）
        2. 获取最优路径的action序列，转换为UP、DOWN、LEFT、RIGHT
        3. 用空格分隔所有token，组合成完整序列
        4. 记录optimal path length
        """
        # 获取最优路径
        optimal_actions = self.solve_bfs()
        if optimal_actions is None:
            return None
        
        # 构建网格token序列
        grid_tokens = []
        for r in range(self.size):
            for c in range(self.size):
                pos = (r, c)
                if pos == self.start:
                    grid_tokens.append("START")
                elif pos == self.goal:
                    grid_tokens.append("GOAL")
                elif self.grid[r, c] == 1:
                    grid_tokens.append("WALL")
                else:
                    grid_tokens.append("PATH")
            grid_tokens.append("NEWLINE")
        
        # 构建action token序列
        action_tokens = [self.action_names[a] for a in optimal_actions]
        
        # 组合完整序列：[<bos>, GRID_START, c_1..c_{K²}, GRID_END, PATH_START, a_1..a_T, DONE, <eos>]
        sequence = ["<bos>", "GRID_START"] + grid_tokens + ["GRID_END", "PATH_START"] + action_tokens + ["DONE", "<eos>"]
        
        # 用空格连接
        text_sequence = " ".join(sequence)
        
        return {
            "sequence": text_sequence,
            "optimal_path_length": len(optimal_actions)
        }


class DatasetGenerator:
    def __init__(self, size=7, seed=42, algorithm='prim', num_episodes=100, filename='dataset.json', save_dir='./data'):
        self.maze_generator = MazeGenerator(size=size, seed=seed, algorithm=algorithm)
        self.num_episodes = num_episodes
        self.episodes = []
        self.filename = filename
        self.save_dir = save_dir
        self.metadata = {
            "size": size,
            "seed": seed,
            "algorithm": algorithm,
            "num_episodes": num_episodes,
        }
        
    def generate(self):
        for i in range(self.num_episodes):
            self.episodes.append(self.maze_generator.format_data())
        return self.episodes, self.metadata
    
    def save(self, filename=None):
        if filename is None:
            filename = os.path.join(self.save_dir, self.filename)   
        with open(filename, 'w') as f:
            json.dump(self.episodes, f, indent=4)
        with open(os.path.join(self.save_dir, self.filename.replace('.json', '_metadata.json')), 'w') as f:
            json.dump(self.metadata, f, indent=4)
    
    def generate_text_training_data(self, val_ratio=0.1):
        """
        任务：生成文本格式的训练数据，并划分为train和val
        实现方案：
        1. 为每个episode生成文本序列（每次调用generate()会使用内部rng生成不同的迷宫）
        2. 按val_ratio划分train/val数据集
        3. 保存为json文件，包含sequence和optimal_path_length
        """
        # 生成所有episode的文本数据
        text_data = []
        for i in range(self.num_episodes):
            # 每次生成新的迷宫（使用内部rng，会自动生成不同的迷宫）
            self.maze_generator.generate()
            text_item = self.maze_generator.to_text_sequence()
            if text_item is not None:
                text_data.append(text_item)
        
        # 划分train/val
        # 使用固定的seed确保可复现的划分
        split_rng = random.Random(self.metadata.get('seed', 42))
        split_rng.shuffle(text_data)
        
        val_size = int(len(text_data) * val_ratio)
        val_data = text_data[:val_size]
        train_data = text_data[val_size:]
        
        # 确保保存目录存在
        os.makedirs(self.save_dir, exist_ok=True)
        
        # 保存train数据
        train_filename = os.path.join(self.save_dir, 'train.json')
        with open(train_filename, 'w', encoding='utf-8') as f:
            json.dump(train_data, f, indent=2, ensure_ascii=False)
        
        # 保存val数据
        val_filename = os.path.join(self.save_dir, 'val.json')
        with open(val_filename, 'w', encoding='utf-8') as f:
            json.dump(val_data, f, indent=2, ensure_ascii=False)
        
        # 保存元数据
        metadata = {
            "size": self.maze_generator.size,
            "seed": self.metadata.get('seed'),
            "algorithm": self.maze_generator.algorithm,
            "num_train": len(train_data),
            "num_val": len(val_data),
            "val_ratio": val_ratio
        }
        metadata_filename = os.path.join(self.save_dir, 'training_metadata.json')
        with open(metadata_filename, 'w', encoding='utf-8') as f:
            json.dump(metadata, f, indent=2, ensure_ascii=False)
        
        print(f"训练数据已生成:")
        print(f"  Train: {len(train_data)} 条，保存至 {train_filename}")
        print(f"  Val: {len(val_data)} 条，保存至 {val_filename}")
        print(f"  元数据保存至 {metadata_filename}")
        
        return train_data, val_data, metadata
            
# ================= Usage Example =================
if __name__ == "__main__":
    # 示例1: 单个迷宫的文本序列生成
    print("=" * 50)
    print("示例1: 单个迷宫的文本序列生成")
    print("=" * 50)
    maze = MazeGenerator(size=7, seed=42)
    grid = maze.generate()
    print("Grid:", grid)
    maze.render_ascii()
    
    # 生成文本序列
    text_data = maze.to_text_sequence()
    if text_data:
        print(f"\n文本序列:")
        print(text_data["sequence"])
        print(f"\n最优路径长度: {text_data['optimal_path_length']}")
    
    # # 示例2: 批量生成训练数据
    # print("\n" + "=" * 50)
    # print("示例2: 批量生成训练数据（train/val划分）")
    # print("=" * 50)
    # dataset_gen = DatasetGenerator(
    #     size=7,
    #     seed=42,
    #     algorithm='prim',
    #     num_episodes=1000,
    #     save_dir='./data/7x7_1k'
    # )
    # train_data, val_data, metadata = dataset_gen.generate_text_training_data(val_ratio=0.1)
    
    # # 显示第一条训练数据的示例
    # if train_data:
    #     print(f"\n训练数据示例（第一条）:")
    #     print(f"序列: {train_data[0]['sequence']}")
    #     print(f"最优路径长度: {train_data[0]['optimal_path_length']}")