# -------------------------------------------------------
# Sudoku data collactor opt for our DataBundle format
# -------------------------------------------------------

import json
import os
import numpy as np
import torch
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader, random_split
from .preprocess_sudoku import sudoku_example_to_mdm, sudoku_n_from_raw_len

class SudokuDataset(Dataset):
    """
    Assume we have the all_inputs.npy and all_labels.npy in the data directory
    these can be generated by the sudoku_HRM.py script
    """

    def __init__(self, data_dir: str, sudoku_type: str, mmap: bool = True):
        # we sue mmap if the .npy's size is too large
        self.data_dir = data_dir

        if sudoku_type == "new":
            # infer n from the raw data shape
            raw_sample = np.load(os.path.join(data_dir, "sudoku-train-data.npy"), mmap_mode="r")
            n = sudoku_n_from_raw_len(raw_sample.shape[1])
            self.n = n
            self.n4 = n ** 4
            self.seq_len = 2 * n ** 4

            train_mdm_path = os.path.join(data_dir, f"train_mdm_n{n}.npy")
            test_mdm_path = os.path.join(data_dir, f"test_mdm_n{n}.npy")

            # preprocess the sudoku dataset into an MDM-friendly version
            if not os.path.exists(train_mdm_path):
                labels = np.load(os.path.join(data_dir, "sudoku-train-data.npy"))
                new_labels = np.zeros((len(labels), self.seq_len))
                for i in tqdm(range(len(labels))):
                    new_labels[i], meta = sudoku_example_to_mdm(labels[i])
                    if not meta["givens_ok"]:
                        print(meta["givens_violations"])
                np.save(train_mdm_path, new_labels)
                print(f"train_mdm_n{n}.npy saved")
                self.labels = new_labels
            else:
                labels = np.load(train_mdm_path)
                self.labels = labels

            # also preprocess for the test dataset
            if not os.path.exists(test_mdm_path):
                labels = np.load(os.path.join(data_dir, "sudoku-test-data.npy"))
                new_labels = np.zeros((len(labels), self.seq_len))
                for i in tqdm(range(len(labels))):
                    new_labels[i], meta = sudoku_example_to_mdm(labels[i])
                    if not meta["givens_ok"]:
                        print(meta["givens_violations"])
                np.save(test_mdm_path, new_labels)
                print(f"test_mdm_n{n}.npy saved")
        else:
            raise ValueError(f"Invalid sudoku data type: {sudoku_type}")

        # ad-hoc prompt masking
        self.prompt_mask = np.zeros((len(self.labels), self.seq_len), dtype=bool)
        self.prompt_mask[:, :self.n4] = 1  # first n^4 cells are clue, last n^4 cells are answer

    def __len__(self):
        return self.labels.shape[0]

    def __getitem__(self, idx):
        # np.load with mmap returns a view, copy() to avoid weirdness
        lab = torch.from_numpy(self.labels[idx].copy()).long()
        prompt_mask = torch.from_numpy(self.prompt_mask[idx].copy()).bool()
        return {"labels": lab, "prompt_mask": prompt_mask}


def split_sudoku(data_dir: str, sudoku_type: str, val_ratio: float = 0.05, seed: int = 2025, mmap: bool = False):
    dataset= SudokuDataset(data_dir, sudoku_type, mmap = mmap)
    n = len(dataset)

    # split
    n_val, n_train = int(n * val_ratio), n - int(n * val_ratio)

    # reproducible split
    g = torch.Generator().manual_seed(seed)
    train_data, val_data = random_split(dataset, [n_train, n_val], generator=g)

    return train_data, val_data


if __name__ == "__main__":
    data_dir = "data/sudoku_new"
    train_data, val_data = split_sudoku(data_dir, "new")
    print(len(train_data), len(val_data))
    print(val_data[0])
